name: "set pending status"

on:
  pull_request_target:

# WARNING:
# When extending this action, be aware that $GITHUB_TOKEN allows write access to
# the GitHub repository. This means that it should not evaluate user input in a
# way that allows code injection.

permissions:
  contents: read

jobs:
  action:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
    - name: set pending status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"context": "ofborg-eval", "state": "pending", "target_url": "", "description": "Waiting for OfBorg..."}' \
          "https://api.github.com/repos/ncfavier/nixpkgs/commits/${{ github.event.pull_request.head.sha }}/statuses"
